apiVersion:
kind: Deployment
metadata: 
  name: app-py-deployment
  label:
    app: app-py-hello

 spec:
  replicas: 2
    matchLabels:
      app: app-py-hello

      template:
        metadata: 
          label:
            app: app-py-hello

        spec:
          containers:
          - name: hello-app
            image: DOCKER_IMAGE
            imagePullPolicy: Always
            ports:
            - containerPort: 8080
    strategy:
      type: RollingUpdate
      roollingUpdate:
        maxSurge: 1
        maxUnavailable: 1
        
      
