apiVersion: apps/v1
kind: Deployment
metadata: 
  name: app-py-deployment
  labels:    # Changed from 'label' to 'labels'
    app: app-py-hello
spec:    # Fixed indentation
  replicas: 2
  selector:    # Added missing 'selector' field
    matchLabels:
      app: app-py-hello
  template:    # Fixed indentation
    metadata: 
      labels:    # Changed from 'label' to 'labels'
        app: app-py-hello
    spec:
      containers:
      - name: hello-app
        image: DOCKER_IMAGE
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
  strategy:    # Fixed indentation
    type: RollingUpdate
    rollingUpdate:    # Fixed spelling of 'rollingUpdate'
      maxSurge: 1
      maxUnavailable: 1
