apiVersion: v1
kind: Service
metadata:
  name: frontend-py-service
  labels:
    app: app-py-hello
spec: 
  selector:
    app: app-py-hello
    ports:
    - port: 8080
    targetPort: 8080
    type: LoadBalancer
    
